### PR TITLE
Create CoolPythonPatterns.py

### PR DESCRIPTION
**Pull request by Jayshah6699**
turtle patterns

### CODE REVIEW

**Review by SanjayDevTech — COMMENTED** [review]
Great turtle program... But please move this file to python folder
then change the filename to match the format:
```
username_program.extension
```

**Comment by Jayshah6699** [comment]
Done @SanjayDevTech

**Comment by Jayshah6699** [comment]
@SanjayDevTech now merge all the commits I have done file name change, file move to python folder.

**Comment by Jayshah6699** [comment]
@SanjayDevTech kindly add hacktoberfest-accepted label to my pull request  and merge it in to the master branch

**Pull request merged**
