### PR TITLE
Integrated greet-contributors action

### PR DESCRIPTION
**Pull request by iampavangandhi**
Issue no. #80 

This action greet all the wonderful contributors within a Pull Request. :tada: 

Github Action Link : [greet-contributors-action](https://github.com/marketplace/actions/greet-contributors-action)

### CODE REVIEW

**Comment by SanjayDevTech** [comment]
@iampavangandhi it is again error...
How to solve?

**Comment by iampavangandhi** [comment]
Have you added any testing action in your repo? As this action works completely fine in my repos.

**Comment by SanjayDevTech** [comment]
> Have you added any testing action in your repo? As this action works completely fine in my repos.

In actions tab??
I didn't add any....

**Comment by iampavangandhi** [comment]
Not specifically in action tab generally like the way we give access to GitHub apps.

**Pull request merged**
